version: '3'

services:
### PHP-FPM ### 
  php:
    build:
      context: ./php
      args: 
      - TIMEZONE=${TIMEZONE}
      - CHANGE_SOURCE=${CHANGE_SOURCE}
      - PHP_VERSION=${PHP_VERSION}
    image: lightingbreakdawn-php
    container_name: lightingbreakdawn-php
    restart: always
    volumes:
      - ${WWWROOT}:/data/wwwroot
    ports:
      - 8081:8081
    networks:
      - lightingbreakdawn-net


networks:
  lightingbreakdawn-net:
    driver: bridge